export const STR = {
  CONTRACT_CONDITIONS: ['Contract conditions'],
  FULFILL: ['fulfill'],
  SEARCH_RESULTS: ['Search results'],
  SELECT_TEMPLATE: ['Select Template'],
  ADD_COMMODITY: ['add commodity'],
  APPLY_TEMPLATE: ['apply template'],
  SAVE: ['save'],
  SEND: ['send'],
  SEND_DRAFT: ['send draft'],
  LOCATION: ['Location'],
  FUEL: ['Fuel'],
  WAREHOUSE: ['Warehouse'],
  OPEN_STORE: ['open store'],
  MAX: ['MAX'],
  OUTPUTS: ['Outputs'],
  ACT: ['ACT'],
  VIEW: ['View'],
  CREATE_NEW: ['Create new'],
}
